### PR TITLE
Decreased SolidBrush creation/destruction

### PR DESCRIPTION
**Pull request by BarryNolte**
Built cache for SolidBrush creation, saves about 3-4% on render.  This will have to be modified for large palettes (start destroying least used brushes), but this should be good for the 95% case.

### CODE REVIEW

**Comment by BarryNolte** [comment]
The real win to be had here, I'm sure you've figured out, is the RenderOpen dispose in SetCellCharacter.  That was too much surgery for me ;) and I see you're working on it already.

**Comment by doubleyewdee** [comment]
Oh nice! Yeah this is excellent. We probably want some sort of eviction policy/LRU so we don't overdo caching. Spot on with the changes to improve rendering (I'm slowly getting there) but even then caching these will be a big win. The render cost is still way higher than I'd like it to be so even ~5% incremental improvements here are huge.

I'm going to try and get my Big Render Change branch into a functional state and then take this PR or a modified varinat.

**Comment by doubleyewdee** [comment]
Going to grab this and then implement the LRU stuff over top quickly.

**Comment by BarryNolte** [comment]
I’ve already got it.  Give me a few minutes :)

**Pull request merged**
